/*CARA MENAMPILKAN DATA DENGAN KONDISI TERTENTU*/
 SELECT *FROM `siswa` WHERE jk= 'P';

 /*CARA MENAMPILKAN BEBERAPA/BATAS RECORD PADA TABLE*/
 SELECT *FROM `siswa` LIMIT 3,5;

 /*CARA MENAMPILKAN/MENGURUTKAN BERDASARKAN FIELD TERTENTU*/
 SELECT *FROM `siswa` ORDER BY tgl_lahir DESC;

 /*CARA MENAMPILKAN FIELD MENGGUNAKN FUNCTION*/
 SELECT UPPER(alamat) FROM `siswa`;

 /*CARA MENAMPILKAN BEBERAPA FIELD dengan KONDISI TERTENTU*/
 SELECT nama_lengkap,tmp_lahir,tgl_lahir FROM `siswa` WHERE YEAR(tgl_lahir)='2002';

 /*CARA MEMPERBARUI DATA PADA TABLE*/
 UPDATE `siswa` SET tmp_lahir= 'BANDUNG',tgl_lahir='2003-01-01' WHERE id_siswa='1';

 /*CARA MENGHAPUS DATA/RECORD*/
 DELETE FROM `siswa` WHERE id_siswa='1';
